Us1 studentform
WildCodeSchool/purple-php-2109-project3-powy pull request #10
Opened 2021-12-20 17:03 UTC by MorganeL-pro

The student form is functionnal.

2021-12-21 08:37 UTC, Thomas905 submitted a review, later dismissed
test ok for me in localhost

2021-12-21 13:24 UTC, RomainClair requested changes
You probably should specify what Type you want for every form field

2021-12-21 13:24 UTC, RomainClair commented on src/Controller/RegistrationController.php
> +        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
You should use annotation to control access to controllers

2021-12-21 13:24 UTC, RomainClair commented on src/Entity/User.php
> +     */
Your form seems to offer 4 choices (including null)
Your Constraint may not be consistant with that.
You may take a look at Choices constraints

2021-12-21 13:24 UTC, RomainClair commented on src/Form/RegistrationFormType.php
> +            // ->add('student', StudentType::class)
You should not push dead code

2021-12-21 13:24 UTC, RomainClair commented on src/Form/StudentType.php
> +                    'Mieux gérer les outils digitaux pro' => 6
You shouldn't repeat yourself.
Why not have a constant to represents this choices ?

2021-12-21 15:38 UTC, Carolinecrepin approved these changes
it's ok for me

2021-12-21 15:38 UTC, Carolinecrepin commented
it's ok for me

2021-12-21 16:33 UTC, Carolinecrepin approved these changes
it's ok for me

2021-12-22 08:49 UTC, RomainClair requested changes
It seems you create reference for your StudyLevel, ProfessionalSector and School in your entities that aren't used anywhere...
If it's the case, you shouldn't create useless references

2021-12-22 08:49 UTC, RomainClair commented on src/Entity/ProfessionalSector.php
> +     */
You probably should have validations here

2021-12-22 08:49 UTC, RomainClair commented on src/Entity/StudyLevel.php
> +    private string $name;
You probaby should have validation constraints here, because you have a form associated that don't have validations either

2021-12-22 08:49 UTC, RomainClair commented on src/Entity/School.php
> +    private string $name;
You should have validation constraints here

2021-12-22 08:49 UTC, RomainClair commented on src/Form/StudentType.php
> +                    'Je ne sais pas' => null,
What's the point of the 2 null choices ?

2021-12-22 08:49 UTC, RomainClair commented on src/Entity/Student.php
> +    private int $topic3;
Topics are choices so you should have a choice constraints also

2021-12-22 08:49 UTC, RomainClair commented on src/Entity/User.php
> +     *     message = "Veuillez entrer un numéro de téléphone valide")
You will have valid numbers considered invalid using this regex.
For example +33600000000 is valid
And some people are used to have separators in phone number like . spaces or -
You may use a less strict constraints here like... between 10 to 20 characters ?

2021-12-22 08:49 UTC, RomainClair commented on src/Controller/RegistrationController.php
> +        $formStudent->handleRequest($request);
Your formStudent submission and validation is not verified so why have one ?

2021-12-22 08:49 UTC, RomainClair commented on src/Controller/RegistrationController.php
> +        $formStudent->handleRequest($request);
Reminder : you can't deal with 2 forms in 1 request
May be you should try nested forms ?

2021-12-22 08:49 UTC, RomainClair commented on src/Controller/RegistrationController.php
> +                $entityManager->persist($student);
Your student object have not been validated

2021-12-22 08:49 UTC, RomainClair commented on src/Controller/RegistrationController.php
> +            }
You should launch email validation only when the use was created in the DB

2021-12-22 08:49 UTC, RomainClair commented on src/Security/EmailVerifier.php
> +    public function handleEmailConfirmation(Request $request, UserInterface $user): void
You can access the current user from the service
See : https://symfony.com/doc/current/security.html#fetching-the-user-from-a-service

2021-12-22 08:49 UTC, RomainClair commented on templates/registration/register.html.twig
> +        {{ form_row(studentForm.studyLevel, {
You should not add fields in a form that won't be handled

2021-12-22 10:43 UTC, closed without merging