Front etudiant
WildCodeSchool/purple-php-2109-project3-powy pull request #14
Opened 2021-12-22 07:44 UTC by Thomas905

2021-12-22 09:50 UTC, Carolinecrepin requested changes
you have to modify the cards so that they are the color of the variable (black past).
and put some padding between the faq title and the faq and between the card title and the cards

2021-12-22 10:08 UTC, Carolinecrepin approved these changes, later dismissed
yes ok good!

2021-12-22 14:36 UTC, RomainClair requested changes

2021-12-22 14:36 UTC, RomainClair commented on templates/etudiant/index.html.twig
> +</script>
You should have your JS script in files

2022-01-03 09:34 UTC, elodiedaubie requested changes
Hi!
Great job :+1: , the page looks nice. However, I noticed few things in the code : 
- the naming of files and methods should be in English. You used the french "etudiant" everywhere, it should be "student".
- the name of "etudiant" method in HomeController should be more specific like studentInformations.
- in the template "etudiant" you should include our component instead of repeating the code (like you did for the footer)
- in scss file, the classes naming might be a problem for futures developments because they are too generics
- you have 2 errors with HTML validator

2022-01-04 11:27 UTC, elodiedaubie approved these changes

2022-01-04 13:38 UTC, RomainClair approved these changes

2022-01-04 13:38 UTC, merged