add functionality view profil information
WildCodeSchool/purple-php-2109-project3-powy pull request #20
Opened 2021-12-27 19:47 UTC by Thomas905

2022-01-02 15:34 UTC, elodiedaubie requested changes
Hello there,

Responsiveness is great, and the body bugfix is a great help to appreciate your work.
Still, I noticed few things: 

1.  Profile take an "e" at the end of the word in English : route naming and template file should be corrected.
2. **in src/Controller** : as we will develop other features for the user profile (modifications, deletions, uploading profile picture), we should create a ProfileController.
3. **in assets/styles/profil.scss:** 
- class naming might be a problem for future frontend developments because they are too generics (ex : card, btn, center), they should be more specific like "profil-card" for instance.
- It could be a good idea to use "em" instead of "px" for a better responsiveness
- pink circle around the profile picto is missing
4. in templates/profil/index.html.twig : the sentence "tu n'as pas encore de mentor" should be there

My apologies, I could not find the way to comment each file, so I wrote it all in one comment.

Elodie

2022-01-03 09:43 UTC, elodiedaubie requested changes
Hi again,

Sorry, I still noticed fews things about your corrections : 

- I see you added "profil" word in classes, but it's in french, the english for it is "profile" with an e
- I think you pushed a wrong file (config/packages/security.yaml), I can't see why it in this PR. This is about access control in another PR and might create a problem in the future.
- In profile controller, method naming should be index instead of "profil"

2022-01-04 10:06 UTC, elodiedaubie requested changes
Hello, I finally learned how to comment files directly, so I put my corrections request there.

2022-01-04 10:06 UTC, elodiedaubie commented on assets/styles/profile.scss
> +}
Hello there, "profil" is still in french, it should be in English ("profile") for all the classes names

2022-01-04 10:06 UTC, elodiedaubie commented on src/Controller/ProfileController.php
> +    public function profil(): Response
Hello, profile needs an  "e" at the end to be in english

2022-01-04 10:06 UTC, elodiedaubie commented on templates/components/_header.html.twig
> +            <a href="/profil"><img src="{{ asset('build/images/silhouette-connexion.png') }}" alt="connexion">Mon compte</a>
The link doesn't work anymore ("profile" instead of "profil")

2022-01-04 10:06 UTC, elodiedaubie commented on assets/styles/profile.scss
> +
Hi, the pink circle around the profile picture is missing

2022-01-04 13:30 UTC, elodiedaubie approved these changes, later dismissed

2022-01-05 08:39 UTC, elodiedaubie approved these changes

2022-01-05 08:48 UTC, RomainClair approved these changes

2022-01-05 08:48 UTC, merged