make-register-form
WildCodeSchool/purple-php-2109-project3-powy pull request #25
Opened 2022-01-04 16:54 UTC by Carolinecrepin

2022-01-05 13:52 UTC, elodiedaubie requested changes
Hello! I put some comments on files directly. The form doesn't work because some properties of User Entity are not nullable (such as firstanme, lastname, phone number ...), we should discuss about that

2022-01-05 13:52 UTC, elodiedaubie commented on src/Entity/User.php
> + * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
Hello, this message should be in french

2022-01-05 13:52 UTC, elodiedaubie commented on templates/login/index.html.twig
> +                <a href=""><p>Vous n'avez pas de compte</p></a>
I think the link to register page is missing

2022-01-05 13:52 UTC, elodiedaubie commented on templates/registration/confirmation_email.html.twig
> +    Please confirm your email address by clicking the following link: <br><br>
Les textes de ces pages devraient être en français

2022-01-05 13:52 UTC, elodiedaubie commented on templates/registration/register.html.twig
> +{% block title %}Register{% endblock %}
Le titre devrait être en français

2022-01-05 13:52 UTC, elodiedaubie commented on templates/registration/register.html.twig
> +{% endblock %}
Les termes du formulaire devraient être en français

2022-01-05 15:05 UTC, elodiedaubie requested changes
Thanks for the corrections. As we discussed, we need to add the mandatories fields (User properties) to the form

2022-01-10 09:33 UTC, elodiedaubie requested changes
Hello there, great work! I required only a  change about flash message

2022-01-10 09:33 UTC, elodiedaubie commented on src/Entity/User.php
>      private string $password;
No assert here as we told, it will be in another US

2022-01-10 09:33 UTC, elodiedaubie commented on templates/login/index.html.twig
> +        {% for label, messages in app.flashes %}
I think that the flashes error message display should be in the base.html.twig, bellow the header

2022-01-10 09:33 UTC, elodiedaubie commented on templates/registration/register.html.twig
> +    {% for flash_error in app.flashes('verify_email_error') %}
same here, I think that the flashes error message display should be in the base.html.twig, bellow the header

2022-01-10 10:08 UTC, elodiedaubie approved these changes

2022-01-10 11:15 UTC, RomainClair approved these changes

2022-01-10 11:15 UTC, merged