unsuscribe method
WildCodeSchool/purple-php-2109-project3-powy pull request #33
Opened 2022-01-06 17:07 UTC by Carolinecrepin

2022-01-06 20:52 UTC, Thomas905 commented on migrations/Version20220106102125.php
> +<?php
You can delete the migration file it is not useful otherwise it creates conflicts with other migration files

2022-01-07 11:24 UTC, Thomas905 submitted a review, later dismissed
Good !

2022-01-07 14:53 UTC, RomainClair requested changes

2022-01-07 14:53 UTC, RomainClair commented on src/Controller/ProfileController.php
> +        $entityManager = $this->getDoctrine()->getManager();
You should use the dependency injection mechanism

2022-01-07 14:53 UTC, RomainClair commented on src/Controller/ProfileController.php
> +     */
This controller should probably not be accessible unless you are properly connected to the site.

2022-01-07 14:53 UTC, RomainClair commented on src/Controller/ProfileController.php
> +            $session = new Session();
You should try to get the Session from the Request object (and get the Request by injecting it to the controller) instead of creating a new one.

2022-01-11 13:51 UTC, MorganeL-pro approved these changes, later dismissed

2022-01-11 15:17 UTC, RomainClair requested changes

2022-01-11 15:17 UTC, RomainClair commented on src/Controller/ProfileController.php
> +use Symfony\Component\HttpFoundation\Session\Session;
You probably don't need this one anymore

2022-01-13 08:31 UTC, elodiedaubie approved these changes
"use" has been correctly deleted

2022-01-13 08:46 UTC, RomainClair approved these changes

2022-01-13 08:47 UTC, merged