uploading profile picture
WildCodeSchool/purple-php-2109-project3-powy pull request #35
Opened 2022-01-07 23:15 UTC by Thomas905

2022-01-10 10:21 UTC, MorganeL-pro reviewed
You should do a git pull before a push to avoid conflicts (css files...)
Pictures of users should not be a the repo. You shoud add them to gitignore.

2022-01-10 10:21 UTC, MorganeL-pro commented on assets/styles/app.scss
>  @import 'mentor';
Maybe you should do a git pull before a push to avoid conflicts.

2022-01-11 15:50 UTC, elodiedaubie requested changes
Hello Thomas, I think that you PR needs some cleaning because there are 36 files in it. Some of the files (migrations files for ex) have nothing to do with it

2022-01-11 15:50 UTC, elodiedaubie commented on composer.json
>      },
Hello, I don't understand why we have this file here, It should not be in this PR

2022-01-11 15:50 UTC, elodiedaubie commented on composer.json
>      },
same for the composer.lock

2022-01-11 15:50 UTC, elodiedaubie commented on config/bundles.php
> +    SymfonyCasts\Bundle\VerifyEmail\SymfonyCastsVerifyEmailBundle::class => ['all' => true],
This file should not be there as well

2022-01-11 15:50 UTC, elodiedaubie commented on migrations/Version20220104134712.php
> +        $this->addSql('ALTER TABLE user ADD is_verified TINYINT(1) NOT NULL');
this file should not be here

2022-01-12 08:34 UTC, closed without merging