added a regex on plainpassword
WildCodeSchool/purple-php-2109-project3-powy pull request #37
Opened 2022-01-11 13:47 UTC by MorganeL-pro

2022-01-11 15:01 UTC, elodiedaubie requested changes
Hello, you should probably change the fixtures as well

2022-01-11 15:20 UTC, elodiedaubie submitted a review, later dismissed

2022-01-11 15:41 UTC, RomainClair requested changes

2022-01-11 15:41 UTC, RomainClair commented on src/Form/RegistrationFormType.php
> +                        'pattern' => '/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$/',
You should probably not forbid to to have non alphanumeric characters in a password

2022-01-12 13:58 UTC, elodiedaubie approved these changes

2022-01-13 08:33 UTC, RomainClair approved these changes

2022-01-13 08:33 UTC, merged