upload picture and fix edit user
WildCodeSchool/purple-php-2109-project3-powy pull request #42
Opened 2022-01-12 08:58 UTC by Thomas905

2022-01-12 14:10 UTC, elodiedaubie requested changes
Hello, 
The picture uploading feature works very well!
Unfortunately, I found 2 bugs : 

1.  password changes: I work only if I submit the other form (for personal info modifications and upload profile picture).

2. After I upload a picture: the profile picto on **connection page** isn't displayed anymore.

Also, we don't display **error messages** on this page, it could be a great idea to do so, what do you think about it?

2022-01-12 14:39 UTC, elodiedaubie approved these changes, later dismissed

2022-01-13 09:58 UTC, RomainClair approved these changes, later dismissed

2022-01-13 09:58 UTC, RomainClair commented on config/services.yaml
> +    pictures_directory: '%kernel.project_dir%/public/upload/pictures'
You should add to your installation manual that you have a directory with data

2022-01-13 09:58 UTC, RomainClair commented on src/Service/FileUploader.php
> +        $file->move($this->getTargetDirectory(), $fileName);
You could have access to $this->targetDirectory directly

2022-01-13 14:23 UTC, elodiedaubie submitted a review, later dismissed

2022-01-14 08:38 UTC, elodiedaubie approved these changes

2022-01-14 08:45 UTC, RomainClair approved these changes

2022-01-14 08:45 UTC, merged