fix css and footer
WildCodeSchool/purple-php-2109-project3-powy pull request #45
Opened 2022-01-12 14:12 UTC by Thomas905

2022-01-12 14:48 UTC, MorganeL-pro reviewed
I now have the same problem as before : footer is not fix at the end of the page.

2022-01-13 16:36 UTC, elodiedaubie requested changes
Has we discussed with Bruni, we should use the bootstrap class "mt-auto"

2022-01-14 09:40 UTC, MorganeL-pro reviewed
Code quality to fix :
assets/styles/header.scss
  25:1   error    Space expected between blocks                     empty-line-between-blocks

2022-01-14 09:46 UTC, MorganeL-pro approved these changes

2022-01-14 09:52 UTC, RomainClair approved these changes

2022-01-14 10:38 UTC, elodiedaubie approved these changes

2022-01-14 10:38 UTC, merged