front connexion design
WildCodeSchool/purple-php-2109-project3-powy pull request #5
Opened 2021-12-16 09:15 UTC by Thomas905

2021-12-16 09:24 UTC, MorganeL-pro approved these changes, later dismissed

2021-12-16 14:44 UTC, elodiedaubie submitted a review, later dismissed

2021-12-17 09:05 UTC, RomainClair requested changes

2021-12-17 09:05 UTC, RomainClair commented on templates/login/index.html.twig
> +        </form>
Your login form is not CSRF protected, you probably should.
C.f. : https://symfony.com/doc/current/security.html#csrf-protection-in-login-forms

2021-12-17 09:14 UTC, elodiedaubie approved these changes, later dismissed

2021-12-17 09:21 UTC, RomainClair requested changes
You also need to ask symfony to check the csrf token on login by enabling it in the security.yaml

2021-12-17 10:05 UTC, elodiedaubie submitted a review, later dismissed

2021-12-17 10:11 UTC, elodiedaubie approved these changes

2021-12-17 10:19 UTC, elodiedaubie approved these changes

2021-12-17 10:23 UTC, RomainClair approved these changes

2021-12-17 10:23 UTC, merged