Us36 password reset
WildCodeSchool/purple-php-2109-project3-powy pull request #54
Opened 2022-01-16 17:07 UTC by MorganeL-pro

Added :
- methods in LoginController to reset password in 2 steps (first : send an email, second : change password)
- views with forms (one with only email for the first step, and second with editpasswordform to change only password)
- templates for mail (one with the link to let the user be redirected to the editpassword, second to confirm the changes)

Changed :
- regex on password in EditPassWordType

2022-01-17 11:47 UTC, elodiedaubie requested changes
Hi there, sorry but I couldn't make this feature work, when I try to modify my password (Testmotdepasse1!), nothing happens. I can't see why

2022-01-17 12:37 UTC, MorganeL-pro commented
> Hi there, sorry but I couldn't make this feature work, when I try to modify my password (Testmotdepasse1!), nothing happens. I can't see why
It seems there is a pb with the accounts created in fixtures. Try with a new account and the method works fine. (But this is weird)

2022-01-17 14:31 UTC, elodiedaubie submitted a review, later dismissed

2022-01-18 12:45 UTC, elodiedaubie approved these changes

2022-01-18 13:09 UTC, RomainClair approved these changes

2022-01-18 13:09 UTC, merged