Us8 choice editor
WildCodeSchool/purple-php-2109-project3-powy pull request #62
Opened 2022-01-22 17:06 UTC by MorganeL-pro

Added a new function to edit topics for a user
I redirected the users who have already an active mentoring.
I injected MatchManager for the student with no mentoring yet.

(added fixtures for mentoring (that i already pulled for us22) to check the method)

2022-01-24 08:51 UTC, Thomas905 submitted a review, later dismissed

2022-01-24 10:35 UTC, RomainClair requested changes

2022-01-24 10:35 UTC, RomainClair commented on src/Controller/ProfileController.php
>                  $this->addFlash(
isVerified is a method from the User class, you should use it directly

2022-01-24 10:35 UTC, RomainClair commented on src/Controller/ProfileController.php
> +        $user = $this->checkUser($id);
Again : could be replaced by paramConverter

2022-01-24 15:46 UTC, Thomas905 approved these changes, later dismissed

2022-01-24 17:06 UTC, Thomas905 approved these changes

2022-01-25 08:21 UTC, RomainClair approved these changes

2022-01-25 08:21 UTC, RomainClair commented on src/Controller/ProfileController.php
> +            if ($user == null || ($user !== null && !$user->getIsVerified())) {
If $user is an instance of User it's not null

2022-01-25 08:21 UTC, RomainClair commented on src/Controller/ProfileController.php
> +            if ($user == null || ($user !== null && !$user->getIsVerified())) {
Using lazy operators the right way can probably simplify this test and merge the previous one

2022-01-25 08:21 UTC, merged