error message in form registration
WildCodeSchool/purple-php-2109-project3-powy pull request #71
Opened 2022-01-25 10:47 UTC by Thomas905

2022-01-25 15:12 UTC, Carolinecrepin requested changes
Missing constraints for age on the mentor and student sides.
For the phone number, a constraint is missing to be allowed to display only numbers.
And there is a problem with the gender constraint, it gives an error if you choose "don't want to say".

try to add the constraint "more than" 17 so that it blocks all those who are less than 18 years old

2022-01-25 15:12 UTC, Carolinecrepin commented on src/Form/RegistrationFormType.php
> +                    ])]
the person must be of age to be able to register so there must be a minimum age constraint at 18 years old

2022-01-25 15:12 UTC, Carolinecrepin commented on src/Form/RegistrationFormType.php
> +            ])
I have to add a constraint because if I put letters instead of numbers it works too.

2022-01-25 15:12 UTC, Carolinecrepin commented on src/Form/RegistrationFormType.php
> +                    ])
the constraint works but it is also put in place when the person does not wish to disclose his gender

2022-01-25 15:12 UTC, Carolinecrepin commented on src/Form/MentorType.php
> +            ])
same problem for the phone number where you can write letters

2022-01-26 15:14 UTC, Carolinecrepin requested changes
it just misses the constraint less than 18 years old on the student form ;) but otherwise it's ok !

2022-01-27 10:21 UTC, Carolinecrepin submitted a review, later dismissed

2022-01-27 10:53 UTC, MorganeL-pro approved these changes
Maybe add a message if a form is submitted but not valid to explain to the user why the form is back to the start.

2022-01-27 10:53 UTC, Carolinecrepin approved these changes

2022-01-27 10:54 UTC, Carolinecrepin approved these changes

2022-01-27 11:30 UTC, merged